### ISSUE TITLE
Outgoing --route does not work

### ISSUE THREAD

**Issue by severach** [hehol/t38modem#6]
[t38modem](https://aur.archlinux.org/packages/t38modem) 4.6.0, opal 3.18.7, ptlib 2.18.7

```
--route "modem:.*=sip:<dn>@voip.xxx.xxx:5060"

cleared (Call failed due to a transport error)
from t38:F7d0a7e5e2 to 15170000000@+/tmp/devt38modem/ttyAC0, route to sip:15170000000@+%2Ftmp%2Fdevt38modem%2FttyAC0
```

This route command does not work. I always get those errors. All I've figured out how to do is to apply this patch, use sed to sub in the `@SIPSVR@`, and compile the voip server into the executable. Each voip server requires a separate compile.

```patch
0001-t38modem-t38fax-routing-support.patch
diff -pNaru5 a/opal/modemep.cxx b/opal/modemep.cxx
--- a/opal/modemep.cxx<>2020-10-27 23:21:29.000000000 -0400
+++ b/opal/modemep.cxx<>2022-01-18 01:13:47.288427748 -0500
@@ -279,11 +279,11 @@ void ModemEndPoint::OnMyCallback(PObject
.
     if (command == "dial") {
       PseudoModem *modem = pmodem_pool->Dequeue(modemToken);
       if (modem != NULL) {
         PString partyA = m_prefix + request("localpartyname");
-        PString partyB = request("number") + "@" + modem->ttyName();
+        PString partyB = request("number") + "@@SIPSVR@";
.
         PString originalPartyB;
         long tries = request("trynextcount").AsInteger();
.
         if (tries++ > 0) {
```

Then calls work. I know `modem->ttyName()` is wrong. How do I fix this to use the command line --route so a single compile will handle all voip servers?

```
from t38:Fb49c3fef8 to 16100000000@voip.xxx.xxx:5060, route to sip:16100000000@voip.xxx.xxx:5060
```

**Comment by hehol** [comment]
The regular expressions in OPAL have changed. I noticed this just recently because some of the sample regular expressions still work.

You can see how the regular expressions are being interpreted in trace level 4.

What used to be

`[source technology]:[expression]=[destination technology]:[replacement]`

now has to be

`[caller technology]:[expression][tab][callee technology]:[expression]=[destination technology]:[replacement]`

In your case this would be

`modem:.*\tsip.*=sip:<dn>@voip.xxx.xxx:5060`

Because of the tab character in the route, I suggest to put the routes in a file and to use the command line paramter

--route @/path/to/your/routes/file

**Comment by severach** [comment]
Embedding the tab is easy in bash.

That didn't help. Looks to me that Opal was already translating to the new route format. The log show the translated output, displayed with a comma instead of a tab.

```
Before
    --route "modem:.*=sip:<dn>@${g_sip_ip}" # Hylafax send fax routes to sip.
    --route "sip:.*=modem:<dn>"             # Receive fax routes to Hylafax receive.

Route table:
  modem:.*,.*=sip:<dn>@voip.???.com:5060
  sip:.*,.*=modem:<dn>
```
```
After
    --route $'modem:.*\t'"sip.*=sip:<dn>@${g_sip_ip}" # Hylafax send fax routes to sip.
    --route $'sip:.*\t.*=modem:<dn>'                  # Receive fax routes to Hylafax receive.

Route table:
  modem:.*,sip.*=sip:<dn>@voip.???.com:5060
  sip:.*,.*=modem:<dn>
```
```
Call[C30e1caaa1] from t38:F1341dae42 to 15170000000@+/tmp/devt38modem/ttyT0, route to sip:15170000000@+%2Ftmp%2Fdevt38modem%2FttyT0
Call[C30e1caaa1] cleared (Call failed due to a transport error)
```

**Comment by jameswillhoite** [comment]
Seems weird. I can get `--route "t38:.*=sip:<dn>@127.0.0.1"` to fax out as long as the receiving line is T.38 compatible.  but no matter what I put in for `--route "modem:.*=sip:<dn>127.0.0.1"` it causes the `(Call failed due to a transport error)`. So normal faxes to an actual fax modem fails

**Comment by hehol** [comment]
@severach, please replace the `modem` endpoint technology with `fax` or `t38`. `modem` is deprecated in releases 4.6.0 and newer. `fax` will work with T.38 and G.711 audio calls while `t38` will switch the connection to T.38 after the call has been answered.

Sorry for not pointing this out in the first place.

**Comment by jameswillhoite** [comment]
My earlier comment was an issue with the Zultys Box. There was not an Outgoing Sip entry for the number I was using. I can can confirm that `--route "fax:.*=sip:<dn>127.0.0.1:5060" --route "sip:.*=fax:<dn>"` does work.

**Comment by severach** [comment]
I switched route to fax: and tried jameswillhoite command from #8, slightly fixed, and routing worked. Turns out the difference is that he is using -a --audio to force G711. I want t38 so I don't use that switch. Here is the logged difference:

```
from t38:Ffe55daa22 to 15170000000@+/dev/ttyT0, route to sip:15170000000@+%2Fdev%2FttyT0
from fax:F22297e602 to 15170000000@+/dev/ttyx0, route to sip:15170000000@192.168.1.30:5040
```

His routes from fax:, mine routes from t38:. With only a --route modem:, or in this case, a --route fax:, all other from have no route. Opal makes up a garbage route. My patch changed the destination to the sip server so opal's made up garbage route was the real route. The solution is specify a route for every possible source. Both forms work.

```
    --route   $'fax:.*\t'".*=sip:<dn>@${g_sip_ip}"
    --route   $'t38:.*\t'".*=sip:<dn>@${g_sip_ip}"
    --route $'modem:.*\t'".*=sip:<dn>@${g_sip_ip}"
    #--route   "fax:.*=sip:<dn>@${g_sip_ip}"
    #--route   "t38:.*=sip:<dn>@${g_sip_ip}"
    #--route "modem:.*=sip:<dn>@${g_sip_ip}"
```

Here they are in more compact form.

```
    --route={fax:,t38:,modem:}$'.*\t'".*=sip:<dn>@${g_sip_ip}"
    #--route={fax:,t38:,modem:}".*=sip:<dn>@${g_sip_ip}"
```
