### ISSUE TITLE
Q.931 [0x4f] Service or option not implemented, unspecified

### ISSUE THREAD

**Issue by jameswillhoite** [hehol/t38modem#8]
I was able to get Ptlib 2.18.8, Opal 3.18.8, t38modem 4.6.2 to build correctly on my Ubuntu 22.04.4 LTS system. Installed Hylafax and have been able to successfully send faxes via my Zultys phone system, but internally only. When testing from the t38modem to my fax line provided via Zultys, the fax came through. When trying to dial an outside line, I get a no carrier detected with the error Q.931[0x4f] as the error.

I'm creating a modem with the following command `/usr/bin/t38modem -ttt -a -o /var/log/t38modem0.log --ptty +/dev/ttyx0 --route "modem:.*,sip.*=sip:<dn>@192.168.1.30:5060" --route "sip:.*,.*=modem:<dn>" -S udp$*:5060 --sip-proxy root@192.168.1.30:5060`

Here is a snip of the log file 

0:16.878	   Opal Listener:131442	      sippdu.cxx(2484)	SIP     	PDU 501  Not Implemented received: rem=udp$192.168.1.30:5060,local=udp$192.168.1.27:5060,if=192.168.1.27%eth0,id=z9hG4bKd8df558c-3f72-5f1f-8bf0-00155d01080d
  0:16.878	        SIP Pool:131478	       sipep.cxx(2428)	SIP     	Handling PDU "1 INVITE <501> z9hG4bKd8df558c-3f72-5f1f-8bf0-00155d01080d" for transaction=z9hG4bKd8df558c-3f72-5f1f-8bf0-00155d01080d
  0:16.879	        SIP Pool:131478	      sippdu.cxx(2615)	SIP     	Sending PDU ACK sip:8655123499@192.168.1.27:5060 (425 bytes) to: rem=udp$192.168.1.30:5060,local=udp$192.168.1.27:5060,if=192.168.1.27%eth0
  0:16.879	        SIP Pool:131478	  connection.cxx(1728)	OpalCon 	Setting phase from ProceedingPhase to ReleasingPhase for Call[C5b8f8a522]-EP<sip>[e493548c-3f72-5f1f-8bed-00155d01080d]
  0:16.879	        SIP Pool:131478	  connection.cxx(405)	OpalCon 	Call end reason for Call[C5b8f8a522]-EP<sip>[e493548c-3f72-5f1f-8bed-00155d01080d] set to EndedByQ.931[0x4f]
  0:16.880	        SIP Pool:131478	  connection.cxx(1728)	OpalCon 	Setting phase from ProceedingPhase to ReleasingPhase for Call[C5b8f8a522]-EP<sip>[e8f9538c-3f72-5f1f-8bea-00155d01080d]
  0:16.880	        SIP Pool:131478	  connection.cxx(405)	OpalCon 	Call end reason for Call[C5b8f8a522]-EP<sip>[e8f9538c-3f72-5f1f-8bea-00155d01080d] set to EndedByQ.931[0x4f]
  0:16.880	        SIP Pool:131478	  connection.cxx(467)	OpalCon 	Releasing asynchronously Call[C5b8f8a522]-EP<sip>[e493548c-3f72-5f1f-8bed-00155d01080d]
  0:16.880	        SIP Pool:131478	      osutil.cxx(272)	PTLib   	File handle high water mark set: 51 Thread unblock pipe
  0:16.880	        SIP Pool:131478	      sippdu.cxx(3596)	SIP     	INVITE transaction id=z9hG4bKd8df558c-3f72-5f1f-8bf0-00155d01080d completed.
  0:16.880	       OnRelease:131483	      sipcon.cxx(328)	SIP-Con 	OnReleased: Call[C5b8f8a522]-EP<sip>[e493548c-3f72-5f1f-8bed-00155d01080d]
  0:16.880	       OnRelease:131483	      sipcon.cxx(405)	SIP-Con 	Cancelling 1 invitations.
  0:16.880	       OnRelease:131483	  connection.cxx(965)	OpalCon 	Media streams closed.
  0:16.881	       OnRelease:131483	     manager.cxx(1082)	OpalMan 	OnReleased Call[C5b8f8a522]-EP<sip>[e493548c-3f72-5f1f-8bed-00155d01080d]
  0:16.881	       OnRelease:131483	        call.cxx(173)	Call    	OnReleased Call[C5b8f8a522]-EP<sip>[e493548c-3f72-5f1f-8bed-00155d01080d]
  0:16.881	       OnRelease:131483	      sipcon.cxx(328)	SIP-Con 	OnReleased: Call[C5b8f8a522]-EP<sip>[e8f9538c-3f72-5f1f-8bea-00155d01080d]
  0:16.882	       OnRelease:131483	      osutil.cxx(272)	PTLib   	File handle high water mark set: 52 10PUDPSocket
  0:16.883	       OnRelease:131483	      sippdu.cxx(2615)	SIP     	Sending PDU 501 Not Implemented (549 bytes) to: rem=udp$192.168.1.30:5060,local=udp$192.168.1.27:5060,if=192.168.1.27%eth0
  0:16.884	   Opal Listener:131442	      sippdu.cxx(2484)	SIP     	PDU ACK sip:8655123499@192.168.1.27:5060 received: rem=udp$192.168.1.30:5060,local=udp$192.168.1.27:5060,if=192.168.1.27%eth0,id=z9hG4bK3764396364-6000
  0:16.884	        SIP Pool:131478	       sipep.cxx(2449)	SIP     	Handling connection PDU "1 ACK sip:8655123499@192.168.1.27:5060 z9hG4bK3764396364-6000" for token=e8f9538c-3f72-5f1f-8bea-00155d01080d
  0:16.884	        SIP Pool:131478	      sipcon.cxx(2544)	SIP-Con 	ACK received: ReleasingPhase
  0:16.885	   Opal Listener:131442	      sippdu.cxx(2484)	SIP     	PDU 501  Not Implemented received: rem=udp$192.168.1.30:5060,local=udp$192.168.1.27:5060,if=192.168.1.27%eth0,id=z9hG4bKf47b528c-3f72-5f1f-8be6-00155d01080d
  0:16.885	        SIP Pool:131478	       sipep.cxx(2428)	SIP     	Handling PDU "1 INVITE <501> z9hG4bKf47b528c-3f72-5f1f-8be6-00155d01080d" for transaction=z9hG4bKf47b528c-3f72-5f1f-8be6-00155d01080d
  0:16.886	        SIP Pool:131478	      sippdu.cxx(2615)	SIP     	Sending PDU ACK sip:8655123499@192.168.1.27:5060 (425 bytes) to: rem=udp$192.168.1.30:5060,local=udp$192.168.1.27:5060,if=192.168.1.27%eth0
  0:16.886	        SIP Pool:131478	  connection.cxx(1728)	OpalCon 	Setting phase from ProceedingPhase to ReleasingPhase for Call[C37fe2fe21]-EP<sip>[e248518c-3f72-5f1f-8be3-00155d01080d]
  0:16.886	        SIP Pool:131478	  connection.cxx(405)	OpalCon 	Call end reason for Call[C37fe2fe21]-EP<sip>[e248518c-3f72-5f1f-8be3-00155d01080d] set to EndedByQ.931[0x4f]
  0:16.886	        SIP Pool:131478	  connection.cxx(1728)	OpalCon 	Setting phase from ProceedingPhase to ReleasingPhase for Call[C37fe2fe21]-EP<sip>[a4e1508c-3f72-5f1f-8be0-00155d01080d]
  0:16.887	        SIP Pool:131478	  connection.cxx(405)	OpalCon 	Call end reason for Call[C37fe2fe21]-EP<sip>[a4e1508c-3f72-5f1f-8be0-00155d01080d] set to EndedByQ.931[0x4f]
  0:16.887	        SIP Pool:131478	  connection.cxx(467)	OpalCon 	Releasing asynchronously Call[C37fe2fe21]-EP<sip>[e248518c-3f72-5f1f-8be3-00155d01080d]
  0:16.887	        SIP Pool:131478	      osutil.cxx(272)	PTLib   	File handle high water mark set: 53 Thread unblock pipe
  0:16.887	        SIP Pool:131478	      sippdu.cxx(3596)	SIP     	INVITE transaction id=z9hG4bKf47b528c-3f72-5f1f-8be6-00155d01080d completed.
  0:16.887	       OnRelease:131484	      sipcon.cxx(328)	SIP-Con 	OnReleased: Call[C37fe2fe21]-EP<sip>[e248518c-3f72-5f1f-8be3-00155d01080d]
  0:16.887	       OnRelease:131484	      sipcon.cxx(405)	SIP-Con 	Cancelling 1 invitations.
  0:16.887	       OnRelease:131484	  connection.cxx(965)	OpalCon 	Media streams closed.
  0:16.887	       OnRelease:131484	     manager.cxx(1082)	OpalMan 	OnReleased Call[C37fe2fe21]-EP<sip>[e248518c-3f72-5f1f-8be3-00155d01080d]
  0:16.887	       OnRelease:131484	        call.cxx(173)	Call    	OnReleased Call[C37fe2fe21]-EP<sip>[e248518c-3f72-5f1f-8be3-00155d01080d]
  0:16.887	       OnRelease:131484	      sipcon.cxx(328)	SIP-Con 	OnReleased: Call[C37fe2fe21]-EP<sip>[a4e1508c-3f72-5f1f-8be0-00155d01080d]
  0:16.888	       OnRelease:131484	      osutil.cxx(272)	PTLib   	File handle high water mark set: 54 10PUDPSocket
  0:16.890	       OnRelease:131484	      sippdu.cxx(2615)	SIP     	Sending PDU 501 Not Implemented (549 bytes) to: rem=udp$192.168.1.30:5060,local=udp$192.168.1.27:5060,if=192.168.1.27%eth0
  0:16.891	   Opal Listener:131442	      sippdu.cxx(2484)	SIP     	PDU ACK sip:8655123499@192.168.1.27:5060 received: rem=udp$192.168.1.30:5060,local=udp$192.168.1.27:5060,if=192.168.1.27%eth0,id=z9hG4bK3764374362-6000
  0:16.891	        SIP Pool:131478	       sipep.cxx(2449)	SIP     	Handling connection PDU "1 ACK sip:8655123499@192.168.1.27:5060 z9hG4bK3764374362-6000" for token=a4e1508c-3f72-5f1f-8be0-00155d01080d
  0:16.891	        SIP Pool:131478	      sipcon.cxx(2544)	SIP-Con 	ACK received: ReleasingPhase
  0:16.952	       OnRelease:131479	      sipcon.cxx(405)	SIP-Con 	Cancelling 0 invitations.
  0:16.952	       OnRelease:131479	  connection.cxx(965)	OpalCon 	Media streams closed.
  0:16.952	       OnRelease:131479	     manager.cxx(1082)	OpalMan 	OnReleased Call[Cce365f366]-EP<sip>[b4ea5f8c-3f72-5f1f-8c12-00155d01080d]
  0:16.952	       OnRelease:131479	        call.cxx(173)	Call    	OnReleased Call[Cce365f366]-EP<sip>[b4ea5f8c-3f72-5f1f-8c12-00155d01080d]
  0:16.952	       OnRelease:131479	     manager.cxx(753)	T38Modem	Call[Cce365f366] cleared (EndedByCapabilityExchange)
  0:16.953	       OnRelease:131479	     manager.cxx(828)	OpalMan 	OnClearedCall Call[Cce365f366] from "sip:8655463040@192.168.1.30:5060" to "sip:8655123499@192.168.1.27:5060"
  0:16.953	       OnRelease:131479	  connection.cxx(1728)	OpalCon 	Setting phase from ReleasingPhase to ReleasedPhase for Call[Cce365f366]-EP<sip>[b4ea5f8c-3f72-5f1f-8c12-00155d01080d]
  0:16.953	       OnRelease:131479	  connection.cxx(522)	OpalCon 	Connection Call[Cce365f366]-EP<sip>[b4ea5f8c-3f72-5f1f-8c12-00155d01080d] released
        Initial Time: Tue, 20 Feb 2024 09:17:55 -05:00
          SetUpPhase: 0.001
     ProceedingPhase: 0.013
       AlertingPhase: N/A
      ConnectedPhase: N/A
    EstablishedPhase: N/A
     ForwardingPhase: N/A
      ReleasingPhase: 0.018
       ReleasedPhase: 0.122
     Call end reason: EndedByCapabilityExchange

  0:16.953	       OnRelease:131479	     rfc2833.cxx(262)	RFC2833 	Using RTP session 0 on UserInput/RFC2833
  0:16.953	       OnRelease:131479	     rfc2833.cxx(262)	RFC2833 	Using RTP session 0 on NamedSignalEvent
  0:16.953	       OnRelease:131479	  connection.cxx(1728)	OpalCon 	Setting phase from ReleasingPhase to ReleasedPhase for Call[Cce365f366]-EP<sip>[ec3e608c-3f72-5f1f-8c15-00155d01080d]
  0:16.953	       OnRelease:131479	  connection.cxx(522)	OpalCon 	Connection Call[Cce365f366]-EP<sip>[ec3e608c-3f72-5f1f-8c15-00155d01080d] released
        Initial Time: Tue, 20 Feb 2024 09:17:55 -05:00
          SetUpPhase: 0.011
     ProceedingPhase: 0.014
       AlertingPhase: N/A
      ConnectedPhase: N/A
    EstablishedPhase: N/A
     ForwardingPhase: N/A
      ReleasingPhase: 0.015
       ReleasedPhase: 0.120
     Call end reason: EndedByCapabilityExchange

  0:16.953	       OnRelease:131479	     rfc2833.cxx(262)	RFC2833 	Using RTP session 0 on UserInput/RFC2833
  0:16.953	       OnRelease:131479	     rfc2833.cxx(262)	RFC2833 	Using RTP session 0 on NamedSignalEvent
  0:16.953	       OnRelease:131479	     osutils.cxx(2880)	PTLib   	Thread ended: name="OnRelease:131479", id=131479, real=104ms, kernel=0.0s (0%), user=0.0s (0%), both=0.0s (0%)
  0:16.959	       OnRelease:131480	      sipcon.cxx(405)	SIP-Con 	Cancelling 0 invitations.
  0:16.959	       OnRelease:131480	  connection.cxx(965)	OpalCon 	Media streams closed.
  0:16.959	       OnRelease:131480	     manager.cxx(1082)	OpalMan 	OnReleased Call[C67fe5e975]-EP<sip>[10005d8c-3f72-5f1f-8c08-00155d01080d]
  0:16.959	       OnRelease:131480	        call.cxx(173)	Call    	OnReleased Call[C67fe5e975]-EP<sip>[10005d8c-3f72-5f1f-8c08-00155d01080d]
  0:16.959	       OnRelease:131480	     manager.cxx(753)	T38Modem	Call[C67fe5e975] cleared (EndedByQ.931[0x4f])
  0:16.959	       OnRelease:131480	     manager.cxx(828)	OpalMan 	OnClearedCall Call[C67fe5e975] from "sip:8655463040@192.168.1.30:5060" to "sip:8655123499@192.168.1.27:5060"
  0:16.960	       OnRelease:131480	  connection.cxx(1728)	OpalCon 	Setting phase from ReleasingPhase to ReleasedPhase for Call[C67fe5e975]-EP<sip>[10005d8c-3f72-5f1f-8c08-00155d01080d]
  0:16.960	       OnRelease:131480	  connection.cxx(522)	OpalCon 	Connection Call[C67fe5e975]-EP<sip>[10005d8c-3f72-5f1f-8c08-00155d01080d] released
        Initial Time: Tue, 20 Feb 2024 09:17:55 -05:00
          SetUpPhase: 0.001
     ProceedingPhase: 0.014
       AlertingPhase: N/A
      ConnectedPhase: N/A
    EstablishedPhase: N/A
     ForwardingPhase: N/A
      ReleasingPhase: 0.044
       ReleasedPhase: 0.148
     Call end reason: EndedByQ.931[0x4f]

**Comment by hehol** [comment]
It looks as if there is an issue with the negotiation on the outgoing call. t38modem gets a

501 Not Implemented

back from the softswitch at IP address 192.168.1.30. Increase the trace level of t38modem to see the SIP dialog or use some external method to capture the SIP packets to find out more.

**Comment by jameswillhoite** [comment]
It was because of the `--sip-proxy` and using `--route "modem:.*=sip:<dn>@..."` once I figured out the `--route "fax:.*=sip:<dn>@...` everything worked.
